logging:
  level:
    root: info
    io.github.syakuis: trace
    org.springframework.web: info
server:
  port: 8081
spring:
  main:
    banner-mode: console
  kafka:
    bootstrap-servers: localhost:9092